type Link {
  id: String!
  title: String
  url: String!
  context: String!
  tags: [Tag!]
  createdAt: DateTime!
  createdById: String
  createdBy: User
}

input AddLinkInput {
  url: String!
  title: String
  context: String!
  tagIds: [String!]
}

extend type Query {
  links: [Link!]!
  link(id: String!): Link
}

extend type Mutation {
  addLink(input: AddLinkInput): Link
  deleteLink(id: String!): Link
}
